
import java.awt.CardLayout;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ananta
 */
public class FormTampilGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form FormTampilGambarComboBox
     */
    public FormTampilGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbGambar = new javax.swing.JComboBox<>();
        pCardLayout = new javax.swing.JPanel();
        lblLucario = new javax.swing.JLabel();
        lblBlaziken = new javax.swing.JLabel();
        lblZoroark = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnGmbr = new javax.swing.JButton();
        btnGmbrFull = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setText("Pilih Gambar");

        cbGambar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lucario", "Blaziken", "Zoroark" }));
        cbGambar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbGambarItemStateChanged(evt);
            }
        });
        cbGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGambarActionPerformed(evt);
            }
        });

        pCardLayout.setLayout(new java.awt.CardLayout());

        lblLucario.setBackground(new java.awt.Color(255, 255, 255));
        lblLucario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLucario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/lucario.png"))); // NOI18N
        lblLucario.setAlignmentY(0.0F);
        pCardLayout.add(lblLucario, "0");

        lblBlaziken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlaziken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/blaziken.png"))); // NOI18N
        pCardLayout.add(lblBlaziken, "1");

        lblZoroark.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZoroark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/zoroark.png"))); // NOI18N
        pCardLayout.add(lblZoroark, "2");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnGmbr.setText("Form Button");
        btnGmbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGmbrActionPerformed(evt);
            }
        });

        btnGmbrFull.setText("Form Button Full");
        btnGmbrFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGmbrFullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGmbr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGmbrFull)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit)
                    .addComponent(btnGmbr)
                    .addComponent(btnGmbrFull))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGambarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGambarActionPerformed

    private void cbGambarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbGambarItemStateChanged
        CardLayout c1 = (CardLayout)(pCardLayout.getLayout());
        c1.show(pCardLayout, String.valueOf(cbGambar.getSelectedIndex()));
    }//GEN-LAST:event_cbGambarItemStateChanged

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnGmbrFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGmbrFullActionPerformed
        new FormPilihGambarBtnFullScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGmbrFullActionPerformed

    private void btnGmbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGmbrActionPerformed
       new FormPilihGambarBtn().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnGmbrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTampilGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTampilGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGmbr;
    private javax.swing.JButton btnGmbrFull;
    private javax.swing.JComboBox<String> cbGambar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBlaziken;
    private javax.swing.JLabel lblLucario;
    private javax.swing.JLabel lblZoroark;
    private javax.swing.JPanel pCardLayout;
    // End of variables declaration//GEN-END:variables
}
